---
- name: node configuration
  hosts: fabchain
  tasks:
  - name: install git, make, upnpc, curl
    with_items: git, make, miniupnpc, curl
    action: "{{ ansible_pkg_mgr }} state=present name={{ item }}"

  - name: install docker
    shell: cd ~ && curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh

  - name: install zenroom
    shell: >
      curl -o /usr/local/bin/zenroom \
      https://files.dyne.org/zenroom/nightly/zenroom-linux-amd64 \
      && chmod +x /usr/local/bin/zenroom

  - name: reboot in the end
    reboot:
  
  - name: Create a login user
    user:
      name: "utente"
      password: "$6$8IAGh7Gu2ugAB.sF$zHldDAEBMoiFUPq2RsGpQ.TRwbPOz3/S5ATs5TbfWDLypYjLGfKN8SNxu1Sx5nNfzQgDJqBh37jT9ln7EIHcq0"
      groups:
        - docker
      state: present
      shell: /bin/bash
      uid: 1000
      home: /home/utente

  - name: log in as root and clone dyneth as utente
    become: true
    become_user: "utente"
    shell: >
      cd ~ \
      && rm -rf dyneth \
      && git clone https://github.com/dyne/dyneth.git
