---
- name: node configuration
  hosts: fabchain
  tasks:
  - name: install git, make, upnpc, curl
    with_items: git, make, miniupnpc, curl
    action: "{{ ansible_pkg_mgr }} state=present name={{ item }}"

  - name: install docker
    shell: cd ~ && curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh

  - name: install zenroom
    shell: >
      curl -o /usr/local/bin/zenroom \
      https://files.dyne.org/zenroom/nightly/zenroom-linux-amd64 \
      && chmod +x /usr/local/bin/zenroom

  - name: reboot in the end
    reboot:

