---
- name: Create the list of bootnodes in enode format
  hosts: sign
  remote_user: app
  vars:
    ansible_remote_tmp: /tmp
  tasks:
  - name: clean local enode files
    local_action: command /bin/rm -f enode*

  - pause:
      seconds: 2

  - name: Generate enode
    command: make command CMD=admin.nodeInfo.enode CONFIG={{ config }}
    register: enode
    args:
      chdir: ~/dyneth

  - debug: var=enode.stdout

  - local_action: copy content="{{ enode.stdout_lines.1 }}" dest="enode-{{ inventory_hostname }}"
