---
- name: Create the list of bootnodes in enr format
  hosts: sign
  remote_user: app
  vars:
    ansible_remote_tmp: /tmp
  tasks:
  - name: copy genesis file on machine
    copy:
      src: genesis.json
      dest: ~/dyneth/data

  - name: Check genesis initialization
    shell: test -r ~/dyneth/data/geth/chaindata/CURRENT && echo "GenesisInitialized" || echo
    register: genesis_initialized
    changed_when: false
  - name: Initialize data/genesis.json
    command: make genesis-init
    args:
      chdir: ~/dyneth
    when: genesis_initialized.stdout != "GenesisInitialized"

  - local_action: command /bin/rm -f enr*

  - name: delete bootnodes.csv
    command: /bin/rm -f ~/dyneth/data/bootnodes.csv

  - name: Stop geth
    command: make stop
    ignore_errors: true
    args:
      chdir: ~/dyneth

  - name: Run signer in background
    command: make run-signer
    args:
      chdir: ~/dyneth

  - pause:
      seconds: 5

  - name: Generate enr
    command: make enr
    register: enr
    args:
      chdir: ~/dyneth

  - debug: var=enr.stdout

  - local_action: copy content="{{ enr.stdout_lines.0 }}" dest="enr-{{ inventory_hostname }}"

  - local_action: command bash join_enr.sh

  - name: Stop geth
    command: make stop
    args:
      chdir: ~/dyneth

  - name: copy bootnodes.csv
    copy:
      src: bootnodes.csv
      dest: ~/dyneth/data

