---
- name: Initialize genesis on all nodes
  hosts: all
  remote_user: app
  vars:
    ansible_remote_tmp: /tmp
    config: "{{ lookup('env','CONFIG') or 'ebsi'}}"
  tasks:

  - name: Check genesis initialization
    shell: test -r ~/dyneth/data/geth/chaindata/CURRENT && echo "GenesisInitialized" || echo
    register: genesis_initialized
    changed_when: false

  - name: Initialize data/genesis.json
    shell: CONFIG={{ config }} make genesis-init
    args:
      chdir: ~/dyneth
    when: genesis_initialized.stdout != "GenesisInitialized"
