---
- name: INSTALL FIREWALL ON SIGNERS
  hosts: sign
  remote_user: root
  vars:
    servers: "{{ lookup('env','SERVERS') }}"
    sign_ports: "{{ lookup('env','SIGN_PORTS') }}"
  tasks:
  - name: install package dependencies
    ansible.builtin.package:
      name:
        - ufw
      state: latest
  - name: Setup UFW firewall
    community.general.ufw:
      state: reset
  - name: limit SSH connections
    community.general.ufw:
      rule: limit
      port: ssh
      proto: tcp
  - name: limit TCP connections
    community.general.ufw:
      rule: limit
      port: "{{ item }}"
      proto: tcp
    loop: "{{ sign_ports }}"
  - name: limit UDP connections
    community.general.ufw:
      rule: limit
      port: "{{ item }}"
      proto: udp
    loop: "{{ sign_ports }}"
  - name: Allow access from dyneth network
    community.general.ufw:
      rule: allow
      src: "{{ item }}"
    loop: "{{ servers }}"
  - name: Setup UFW firewall
    community.general.ufw:
      state: enabled
      policy: deny
