---
- name: Dyneth node installation
  hosts: fabchain
  remote_user: root
  vars:
    geth_pass: "{{ lookup('password','/tmp/passfile length=64 chars=ascii_letters,digits') }}"
    dyneth_repo: "{{ lookup('env','DYNETH_REPO') or 'https://github.com/dyne/dyneth'}}"
    ansible_remote_tmp: /tmp
  tasks:
  - name: Update and upgrade apt packages
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: install package dependencies
    ansible.builtin.package:
      name:
        - make
        - miniupnpc
        - curl
        - git
        - tree
        - tmux
        - jq
      state: latest

  - name: check docker installed
    shell: command -v docker>/dev/null && echo "DockerInstalled" || echo
    register: docker_installed
    changed_when: false

  - name: install docker
    shell: >
      cd ~ && curl -fsSL https://get.docker.com -o get-docker.sh \
      && sudo sh get-docker.sh
    when: docker_installed.stdout != "DockerInstalled"

  - name: check zenroom installed
    shell: command -v zenroom>/dev/null && echo "ZenroomInstalled" || echo
    register: zenroom_installed
    changed_when: false

  - name: install zenroom
    shell: >
      curl -o /usr/local/bin/zenroom \
      https://files.dyne.org/zenroom/nightly/zenroom-linux-amd64 \
      && chmod +x /usr/local/bin/zenroom;
    register: cmd_result
    when: zenroom_installed.stdout != "ZenroomInstalled"
  
  - name: Create a login user
    user:
      name: "app"
      groups:
        - docker
      state: present
      shell: /bin/bash
      uid: 1000
      home: /home/app

  - name: log in as root and clone dyneth as app
    become: true
    become_user: "app"
    shell:
      cd ~ \
      && rm -rf dyneth \
      && git clone {{ dyneth_repo }} dyneth \
      && cd dyneth \
      && make account PASS={{ geth_pass }}
    register: geth_account_pass

  - name: copy ssh keys from root to app
    shell:
      cp -ra ~/.ssh /home/app/ \
      && chown -R app:app /home/app/.ssh

  - name: log geth address
    debug: var=geth_account_pass.stdout
