---
- name: FABCHAIN FIREWALL SETUP
  hosts: api
  remote_user: root
  vars:
    api_ports: "{{ lookup('env','API_PORTS') }}"
    signers: "{{ lookup('env','SIGNERS') }}"
  tasks:
  - name: install package dependencies
    ansible.builtin.package:
      name:
        - ufw
      state: latest
  - name: Setup UFW firewall
    community.general.ufw:
      state: reset
  - name: Allow all access from signers
    community.general.ufw:
      rule: allow
      src: "{{ item }}"
    loop: "{{ signers }}"
  - name: limit SSH connections
    community.general.ufw:
      rule: limit
      port: ssh
      proto: tcp
  - name: Allow API tcp connections
    community.general.ufw:
      rule: allow
      port: "{{ item }}"
      proto: tcp
    loop: "{{ api_ports }}"
  - name: Setup UFW firewall
    community.general.ufw:
      state: enabled
      policy: deny
