---
- name: START ALL APIs
  hosts: api
  remote_user: app
  vars:
    ansible_remote_tmp: /tmp
  tasks:
  - command: make stop CONFIG={{ config }}
    args:
      chdir: ~/dyneth
    ignore_errors: yes # Node could be already stopped
  - command: make run CONFIG={{ config }}
    args:
      chdir: ~/dyneth
