---
- name: START ALL SIGNERS
  hosts: sign
  remote_user: app
  vars:
    ansible_remote_tmp: /tmp
  tasks:
  - command: "make CONFIG={{ config }} stop"
    args:
      chdir: ~/dyneth
    ignore_errors: yes # SIgner could be already stopped
  - shell: "CONFIG={{ config }} make run-signer"
    args:
      chdir: ~/dyneth
    when: DOCKER_IMAGE is not defined
  - shell: "DOCKER_IMAGE={{DOCKER_IMAGE}} CONFIG={{ config }} make run-signer"
    args:
      chdir: ~/dyneth
    when: DOCKER_IMAGE is defined
