---
- name: STOP ALL NODES
  hosts: all
  remote_user: app
  vars:
    ansible_remote_tmp: /tmp
  tasks:
  - name: Stop geth
    command: make stop
    ignore_errors: true
    args:
      chdir: ~/dyneth
