---
- name: UPGRADE ALL SERVERS
  hosts: all
  remote_user: app
  tasks:

  - name: pull git repo
    shell: git checkout . && git pull --rebase
    args:
      chdir: ~/dyneth

  - name: pull docker image
    shell: make -C container pull
    args:
      chdir: ~/dyneth
